Console.WriteLine("Enter the value of points A");
Console.Write("Enter the X value for point A: ");
int Ax = Convert.ToInt32(Console.ReadLine());
Console.Write("Enter the Y value for point A: ");
int Ay = Convert.ToInt32(Console.ReadLine());
Console.Write("Enter the Z value for point A: ");
int Az = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Enter the value of points B");
Console.Write("Enter the X value for point B: ");
int Bx = Convert.ToInt32(Console.ReadLine());
Console.Write("Enter the Y value for point B: ");
int By = Convert.ToInt32(Console.ReadLine());
Console.Write("Enter the Z value for point B: ");
int Bz = Convert.ToInt32(Console.ReadLine());
double distance = Math.Sqrt(Math.Pow((Bx - Ax), 2) + Math.Pow((By - Ay), 2) + Math.Pow(Bz - Az, 2));
Console.WriteLine(Math.Round(distance, 2));
